# Generated by Django 5.2.10 on 2026-01-24 15:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        (
            "links",
            "0002_rename_links_short_c_5baf86_idx_links_short_c_95d67d_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("country_code", models.CharField(max_length=2)),
                ("country_name", models.CharField(max_length=100)),
                ("total_clicks", models.IntegerField(default=0)),
                ("unique_clicks", models.IntegerField(default=0)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
            ],
            options={
                "db_table": "country_stats",
                "ordering": ["-total_clicks"],
            },
        ),
        migrations.CreateModel(
            name="ReferrerStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("referer_domain", models.CharField(max_length=255)),
                ("total_clicks", models.IntegerField(default=0)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
            ],
            options={
                "db_table": "referrer_stats",
                "ordering": ["-total_clicks"],
            },
        ),
        migrations.RenameField(
            model_name="clickevent",
            old_name="is_bot",
            new_name="is_qr_scan",
        ),
        migrations.RenameIndex(
            model_name="clickevent",
            new_name="clicks_link_id_861225_idx",
            old_name="click_event_link_id_dd3412_idx",
        ),
        migrations.RenameIndex(
            model_name="clickevent",
            new_name="clicks_clicked_fa0a3b_idx",
            old_name="click_event_clicked_81f3c1_idx",
        ),
        migrations.RemoveField(
            model_name="clickevent",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="clickevent",
            name="is_unique",
        ),
        migrations.RemoveField(
            model_name="dailystats",
            name="browsers",
        ),
        migrations.RemoveField(
            model_name="dailystats",
            name="countries",
        ),
        migrations.RemoveField(
            model_name="dailystats",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="dailystats",
            name="devices",
        ),
        migrations.RemoveField(
            model_name="dailystats",
            name="referrers",
        ),
        migrations.AddField(
            model_name="clickevent",
            name="timezone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="clickevent",
            name="utm_campaign",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="clickevent",
            name="utm_medium",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="clickevent",
            name="utm_source",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="dailystats",
            name="desktop_clicks",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailystats",
            name="mobile_clicks",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailystats",
            name="qr_scans",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailystats",
            name="tablet_clicks",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailystats",
            name="top_country_clicks",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailystats",
            name="top_country_code",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="clickevent",
            name="browser",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="clickevent",
            name="clicked_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="clickevent",
            name="ip_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="clickevent",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="clickevent",
            name="link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clicks",
                to="links.link",
            ),
        ),
        migrations.AlterField(
            model_name="clickevent",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="clickevent",
            name="os",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="clickevent",
            name="referer",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="dailystats",
            name="total_clicks",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dailystats",
            name="unique_clicks",
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="clickevent",
            index=models.Index(
                fields=["country_code"], name="clicks_country_826617_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clickevent",
            index=models.Index(
                fields=["device_type"], name="clicks_device__e6b646_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailystats",
            index=models.Index(
                fields=["link", "-date"], name="daily_stats_link_id_64ded2_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="clickevent",
            table="clicks",
        ),
        migrations.AddField(
            model_name="countrystats",
            name="link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="country_stats",
                to="links.link",
            ),
        ),
        migrations.AddField(
            model_name="referrerstats",
            name="link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrer_stats",
                to="links.link",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="countrystats",
            unique_together={("link", "country_code", "period_start")},
        ),
        migrations.AlterUniqueTogether(
            name="referrerstats",
            unique_together={("link", "referer_domain", "period_start")},
        ),
    ]
