# Generated by Django 5.2.10 on 2026-02-05 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_countrystats_referrerstats_and_more'),
        ('campaigns', '0003_add_team_fk'),
        ('links', '0003_add_team_fk'),
        ('qrcodes', '0007_qrcode_unique_scans'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailystats',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='is_first_scan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='qr_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='qrcodes.qrcode'),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='variant_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('valid', 'Valid'), ('suspicious', 'Suspicious'), ('invalid', 'Invalid')], max_length=20),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='qr_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='qrcodes.qrcode'),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='links.link'),
        ),
        migrations.AlterField(
            model_name='dailystats',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='links.link'),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['qr_code', '-clicked_at'], name='clicks_qr_code_107709_idx'),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['campaign', '-clicked_at'], name='clicks_campaig_b8fe87_idx'),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['serial_number'], name='clicks_serial__35e53c_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystats',
            index=models.Index(fields=['qr_code', '-date'], name='daily_stats_qr_code_347f92_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystats',
            index=models.Index(fields=['campaign', '-date'], name='daily_stats_campaig_ceb42e_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystats',
            index=models.Index(fields=['date'], name='daily_stats_date_c5e813_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailystats',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('campaign__isnull', True), ('link__isnull', False), ('qr_code__isnull', True)), models.Q(('campaign__isnull', True), ('link__isnull', True), ('qr_code__isnull', False)), models.Q(('campaign__isnull', False), ('link__isnull', True), ('qr_code__isnull', True)), _connector='OR'), name='daily_stats_single_entity'),
        ),
    ]
