# Generated by Django 5.2.10 on 2026-01-24 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="link",
            new_name="links_short_c_95d67d_idx",
            old_name="links_short_c_5baf86_idx",
        ),
        migrations.RenameIndex(
            model_name="link",
            new_name="links_user_id_feaab0_idx",
            old_name="links_user_id_e91af3_idx",
        ),
        migrations.RenameIndex(
            model_name="link",
            new_name="links_is_acti_6ddfc2_idx",
            old_name="links_is_acti_5a94c1_idx",
        ),
    ]
