# Generated by Django 5.2.10 on 2026-01-31 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_rename_links_short_c_5baf86_idx_links_short_c_95d67d_idx_and_more'),
        ('teams', '0001_team_collab_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdomain',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_domains', to='teams.team'),
        ),
        migrations.AddField(
            model_name='link',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='teams.team'),
        ),
    ]
