# Generated by Django 5.2.11 on 2026-02-15 03:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0003_add_team_fk"),
        ("teams", "0001_team_collab_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetargetingPixel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook Pixel"),
                            ("google", "Google Ads"),
                            ("tiktok", "TikTok Pixel"),
                            ("twitter", "Twitter/X Pixel"),
                            ("linkedin", "LinkedIn Insight"),
                            ("snapchat", "Snapchat Pixel"),
                            ("pinterest", "Pinterest Tag"),
                            ("custom", "Custom Script"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pixel_id", models.CharField(max_length=255)),
                ("custom_script", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pixels",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pixels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "retargeting_pixels",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="link",
            name="pixels",
            field=models.ManyToManyField(
                blank=True, related_name="links", to="links.retargetingpixel"
            ),
        ),
    ]
