# Generated by Django 5.2.10 on 2026-02-06 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0003_add_team_fk'),
        ('qrcodes', '0008_qrcode_eye_color_qrcode_eye_style_qrcode_frame_text_and_more'),
        ('teams', '0001_team_collab_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('logic', models.CharField(choices=[('and', 'All conditions must match (AND)'), ('or', 'Any condition can match (OR)')], default='and', max_length=10)),
                ('priority', models.IntegerField(default=0)),
                ('action_type', models.CharField(choices=[('redirect', 'Redirect to URL'), ('show_content', 'Show Content Page'), ('block', 'Block Access'), ('add_utm', 'Add UTM Parameters'), ('set_header', 'Set Response Header')], max_length=30)),
                ('action_value', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule_groups', to='links.link')),
                ('qr_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule_groups', to='qrcodes.qrcode')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule_groups', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rule_groups',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition_type', models.CharField(choices=[('country', 'Country'), ('city', 'City'), ('region', 'Region/State'), ('device', 'Device Type'), ('os', 'Operating System'), ('browser', 'Browser'), ('language', 'Language'), ('referrer', 'Referrer Domain'), ('time', 'Time of Day (Hour)'), ('date', 'Date'), ('day_of_week', 'Day of Week'), ('scan_count', 'Scan/Click Count'), ('is_first_scan', 'Is First Scan'), ('query_param', 'Query Parameter')], max_length=30)),
                ('condition_operator', models.CharField(choices=[('eq', 'Equals'), ('neq', 'Not Equals'), ('contains', 'Contains'), ('not_contains', 'Does Not Contain'), ('starts_with', 'Starts With'), ('ends_with', 'Ends With'), ('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('between', 'Between'), ('in', 'In List'), ('not_in', 'Not In List'), ('regex', 'Matches Regex')], max_length=20)),
                ('condition_value', models.JSONField()),
                ('condition_key', models.CharField(blank=True, max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='rules.rulegroup')),
            ],
            options={
                'db_table': 'rule_conditions',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name for this rule', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of rule purpose')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are evaluated first')),
                ('condition_type', models.CharField(choices=[('country', 'Country'), ('city', 'City'), ('region', 'Region/State'), ('device', 'Device Type'), ('os', 'Operating System'), ('browser', 'Browser'), ('language', 'Language'), ('referrer', 'Referrer Domain'), ('time', 'Time of Day (Hour)'), ('date', 'Date'), ('day_of_week', 'Day of Week'), ('scan_count', 'Scan/Click Count'), ('is_first_scan', 'Is First Scan'), ('query_param', 'Query Parameter')], max_length=30)),
                ('condition_operator', models.CharField(choices=[('eq', 'Equals'), ('neq', 'Not Equals'), ('contains', 'Contains'), ('not_contains', 'Does Not Contain'), ('starts_with', 'Starts With'), ('ends_with', 'Ends With'), ('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('between', 'Between'), ('in', 'In List'), ('not_in', 'Not In List'), ('regex', 'Matches Regex')], max_length=20)),
                ('condition_value', models.JSONField(help_text='Value(s) to match against. Format depends on operator.')),
                ('condition_key', models.CharField(blank=True, help_text='Key for query_param conditions', max_length=100)),
                ('action_type', models.CharField(choices=[('redirect', 'Redirect to URL'), ('show_content', 'Show Content Page'), ('block', 'Block Access'), ('add_utm', 'Add UTM Parameters'), ('set_header', 'Set Response Header')], max_length=30)),
                ('action_value', models.JSONField(help_text='Action configuration. Format depends on action type.')),
                ('is_active', models.BooleanField(default=True)),
                ('schedule_start', models.DateTimeField(blank=True, help_text='Rule becomes active at this time', null=True)),
                ('schedule_end', models.DateTimeField(blank=True, help_text='Rule deactivates at this time', null=True)),
                ('times_matched', models.IntegerField(default=0)),
                ('last_matched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='links.link')),
                ('qr_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='qrcodes.qrcode')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rules',
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['link', 'is_active', '-priority'], name='rules_link_id_492d9a_idx'), models.Index(fields=['qr_code', 'is_active', '-priority'], name='rules_qr_code_9cd173_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('link__isnull', False), ('qr_code__isnull', True)), models.Q(('link__isnull', True), ('qr_code__isnull', False)), _connector='OR'), name='rule_must_have_link_or_qrcode')],
            },
        ),
    ]
