# Generated by Django 5.2.10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('qrcodes', '0008_qrcode_eye_color_qrcode_eye_style_qrcode_frame_text_and_more'),
    ]

    operations = [
        # Add campaign FK to Rule
        migrations.AddField(
            model_name='rule',
            name='campaign',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='rules',
                to='campaigns.campaign',
            ),
        ),
        # Add serial_batch FK to Rule
        migrations.AddField(
            model_name='rule',
            name='serial_batch',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='rules',
                to='qrcodes.serialbatch',
            ),
        ),
        # Add campaign FK to RuleGroup
        migrations.AddField(
            model_name='rulegroup',
            name='campaign',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='rule_groups',
                to='campaigns.campaign',
            ),
        ),
        # Add serial_batch FK to RuleGroup
        migrations.AddField(
            model_name='rulegroup',
            name='serial_batch',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='rule_groups',
                to='qrcodes.serialbatch',
            ),
        ),
        # Remove old constraint
        migrations.RemoveConstraint(
            model_name='rule',
            name='rule_must_have_link_or_qrcode',
        ),
        # Add new constraint allowing all four targets
        migrations.AddConstraint(
            model_name='rule',
            constraint=models.CheckConstraint(
                check=(
                    models.Q(link__isnull=False, qr_code__isnull=True, campaign__isnull=True, serial_batch__isnull=True) |
                    models.Q(link__isnull=True, qr_code__isnull=False, campaign__isnull=True, serial_batch__isnull=True) |
                    models.Q(link__isnull=True, qr_code__isnull=True, campaign__isnull=False, serial_batch__isnull=True) |
                    models.Q(link__isnull=True, qr_code__isnull=True, campaign__isnull=True, serial_batch__isnull=False)
                ),
                name='rule_must_have_one_target',
            ),
        ),
        # Add indexes for new targets
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['campaign', 'is_active', '-priority'], name='rules_campai_c1b2a3_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['serial_batch', 'is_active', '-priority'], name='rules_serial_d4e5f6_idx'),
        ),
    ]
