# Generated by Django 5.2.11 on 2026-02-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0002_add_campaign_serial_batch_targets"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="rule",
            new_name="rules_campaig_bf0920_idx",
            old_name="rules_campai_c1b2a3_idx",
        ),
        migrations.RenameIndex(
            model_name="rule",
            new_name="rules_serial__b43686_idx",
            old_name="rules_serial_d4e5f6_idx",
        ),
    ]
