# Generated by Django 5.2.10 on 2026-01-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaign",
            old_name="utm_campaign",
            new_name="default_utm_campaign",
        ),
        migrations.RenameField(
            model_name="campaign",
            old_name="utm_content",
            new_name="default_utm_medium",
        ),
        migrations.RenameField(
            model_name="campaign",
            old_name="utm_medium",
            new_name="default_utm_source",
        ),
        migrations.RenameIndex(
            model_name="campaign",
            new_name="campaigns_user_id_c5fbd0_idx",
            old_name="campaigns_user_id_f18c21_idx",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="ends_at",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="starts_at",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="utm_source",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="utm_term",
        ),
        migrations.AddField(
            model_name="campaign",
            name="total_clicks",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaign",
            name="total_links",
            field=models.IntegerField(default=0),
        ),
    ]
