# Generated by Django 5.2.10 on 2026-02-06 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_add_team_fk'),
        ('links', '0003_add_team_fk'),
        ('qrcodes', '0007_qrcode_unique_scans'),
        ('teams', '0001_team_collab_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('destination_url', models.URLField(max_length=2048)),
                ('weight', models.IntegerField(default=50, help_text='Weight percentage 0-100')),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('is_control', models.BooleanField(default=False, help_text='Is this the control variant')),
                ('is_winner', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'variants',
                'ordering': ['-is_control', '-weight'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='click_budget',
            field=models.IntegerField(blank=True, help_text='Maximum clicks allowed', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='clicks_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='expired_message',
            field=models.TextField(blank=True, default='This campaign has ended.'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='fallback_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='campaign',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='campaigns_status_a03570_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['starts_at'], name='campaigns_starts__e85145_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['ends_at'], name='campaigns_ends_at_303532_idx'),
        ),
        migrations.AddField(
            model_name='variant',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='links.link'),
        ),
        migrations.AddField(
            model_name='variant',
            name='qr_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='qrcodes.qrcode'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['link', 'is_active'], name='variants_link_id_ca9f97_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['qr_code', 'is_active'], name='variants_qr_code_5c1de5_idx'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('link__isnull', False), ('qr_code__isnull', True)), models.Q(('link__isnull', True), ('qr_code__isnull', False)), _connector='OR'), name='variant_single_parent'),
        ),
    ]
