# Generated by Django 5.2.10 on 2026-01-24 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "links",
            "0002_rename_links_short_c_5baf86_idx_links_short_c_95d67d_idx_and_more",
        ),
        ("qrcodes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="qrcode",
            name="qr_codes_user_id_5b7a2c_idx",
        ),
        migrations.RenameField(
            model_name="qrcode",
            old_name="image_file",
            new_name="pdf_path",
        ),
        migrations.RemoveField(
            model_name="qrcode",
            name="error_correction",
        ),
        migrations.RemoveField(
            model_name="qrcode",
            name="include_margin",
        ),
        migrations.RemoveField(
            model_name="qrcode",
            name="size",
        ),
        migrations.AddField(
            model_name="qrcode",
            name="png_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="style",
            field=models.CharField(
                choices=[
                    ("square", "Square"),
                    ("dots", "Dots"),
                    ("rounded", "Rounded"),
                ],
                default="square",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="svg_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="qrcode",
            name="link",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qr_code",
                to="links.link",
            ),
        ),
    ]
