# Generated by Django 5.2.10 on 2026-01-24 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_rename_links_short_c_5baf86_idx_links_short_c_95d67d_idx_and_more'),
        ('qrcodes', '0002_remove_qrcode_qr_codes_user_id_5b7a2c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='content_data',
            field=models.JSONField(blank=True, default=dict, help_text='Type-specific content data (vcard, wifi, etc.)'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='is_dynamic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='qr_type',
            field=models.CharField(choices=[('link', 'Website Link'), ('vcard', 'Contact Card'), ('wifi', 'WiFi Network'), ('email', 'Email'), ('sms', 'SMS Message'), ('phone', 'Phone Call'), ('text', 'Plain Text'), ('calendar', 'Calendar Event'), ('location', 'Location')], default='link', max_length=20),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='short_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='title',
            field=models.CharField(blank=True, help_text='User-friendly name for this QR code', max_length=200),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='links.link'),
        ),
    ]
