# Generated by Django 5.2.10 on 2026-01-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qrcodes", "0003_add_qr_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="frame",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("simple", "Simple Border"),
                    ("scan_me", "Scan Me"),
                    ("balloon", "Balloon"),
                    ("badge", "Badge"),
                    ("phone", "Phone Mockup"),
                    ("polaroid", "Polaroid"),
                    ("laptop", "Laptop Mockup"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
