# Generated by Django 5.2.10 on 2026-01-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qrcodes", "0004_qrcode_frame"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="destination_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
