# Generated by Django 5.2.10 on 2026-01-31 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0005_qrcode_destination_url'),
        ('teams', '0001_team_collab_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='teams.team'),
        ),
    ]
