# Generated by Django 5.2.10 on 2026-02-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0006_add_team_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='unique_scans',
            field=models.BigIntegerField(default=0),
        ),
    ]
