# Generated by Django 5.2.10 on 2026-02-06 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0007_qrcode_unique_scans'),
        ('teams', '0001_team_collab_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='eye_color',
            field=models.CharField(blank=True, help_text='Separate color for QR eyes/corners', max_length=7),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='eye_style',
            field=models.CharField(choices=[('square', 'Square'), ('circle', 'Circle'), ('rounded', 'Rounded'), ('leaf', 'Leaf'), ('diamond', 'Diamond')], default='square', max_length=20),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='frame_text',
            field=models.CharField(blank=True, help_text='Custom text for frame label', max_length=50),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='gradient_direction',
            field=models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('diagonal', 'Diagonal'), ('radial', 'Radial')], default='vertical', max_length=20),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='gradient_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='gradient_end',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='gradient_start',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='frame',
            field=models.CharField(choices=[('none', 'None'), ('simple', 'Simple Border'), ('scan_me', 'Scan Me'), ('balloon', 'Balloon'), ('badge', 'Badge'), ('phone', 'Phone Mockup'), ('polaroid', 'Polaroid'), ('laptop', 'Laptop Mockup'), ('ticket', 'Event Ticket'), ('card', 'Business Card'), ('tag', 'Product Tag'), ('certificate', 'Certificate')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qr_type',
            field=models.CharField(choices=[('link', 'Website Link'), ('vcard', 'Contact Card'), ('wifi', 'WiFi Network'), ('email', 'Email'), ('sms', 'SMS Message'), ('phone', 'Phone Call'), ('text', 'Plain Text'), ('calendar', 'Calendar Event'), ('location', 'Location'), ('upi', 'UPI Payment'), ('pix', 'Pix Payment (Brazil)'), ('product', 'Product Information'), ('menu', 'Restaurant Menu'), ('document', 'Document/File'), ('pdf', 'PDF Document'), ('multi_url', 'Multiple Links'), ('app_store', 'App Store Links'), ('social', 'Social Media Hub'), ('serial', 'Serialized Product')], default='link', max_length=20),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='style',
            field=models.CharField(choices=[('square', 'Square'), ('dots', 'Dots'), ('rounded', 'Rounded'), ('diamond', 'Diamond'), ('star', 'Star')], default='square', max_length=20),
        ),
        migrations.CreateModel(
            name='SerialBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prefix', models.CharField(blank=True, help_text="Prefix for serial numbers (e.g., 'PROD-')", max_length=20)),
                ('quantity', models.IntegerField(help_text='Number of QR codes to generate')),
                ('generated_count', models.IntegerField(default=0)),
                ('destination_url_template', models.URLField(blank=True, help_text='URL template with {serial} placeholder for serial number', max_length=2048)),
                ('style', models.CharField(choices=[('square', 'Square'), ('dots', 'Dots'), ('rounded', 'Rounded'), ('diamond', 'Diamond'), ('star', 'Star')], default='square', max_length=20)),
                ('frame', models.CharField(choices=[('none', 'None'), ('simple', 'Simple Border'), ('scan_me', 'Scan Me'), ('balloon', 'Balloon'), ('badge', 'Badge'), ('phone', 'Phone Mockup'), ('polaroid', 'Polaroid'), ('laptop', 'Laptop Mockup'), ('ticket', 'Event Ticket'), ('card', 'Business Card'), ('tag', 'Product Tag'), ('certificate', 'Certificate')], default='none', max_length=20)),
                ('foreground_color', models.CharField(default='#000000', max_length=7)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('product_sku', models.CharField(blank=True, max_length=100)),
                ('product_category', models.CharField(blank=True, max_length=100)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('batch_metadata', models.JSONField(blank=True, default=dict)),
                ('export_format', models.CharField(choices=[('zip', 'ZIP Archive'), ('csv', 'CSV Only')], default='zip', max_length=10)),
                ('export_file_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serial_batches', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Serial batches',
                'db_table': 'serial_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SerialCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('first_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('first_scan_ip_hash', models.CharField(blank=True, max_length=64)),
                ('first_scan_location', models.CharField(blank=True, max_length=200)),
                ('first_scan_country', models.CharField(blank=True, max_length=2)),
                ('first_scan_city', models.CharField(blank=True, max_length=100)),
                ('first_scan_device', models.CharField(blank=True, max_length=100)),
                ('total_scans', models.IntegerField(default=0)),
                ('unique_ips', models.IntegerField(default=0)),
                ('unique_locations', models.IntegerField(default=0)),
                ('unique_countries', models.IntegerField(default=0)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('last_scan_location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspicious', 'Suspicious'), ('blocked', 'Blocked'), ('recalled', 'Recalled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('status_reason', models.TextField(blank=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('suspicion_score', models.IntegerField(default=0, help_text='0-100 score, higher = more suspicious')),
                ('suspicion_reasons', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='qrcodes.serialbatch')),
                ('qr_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='serial', to='qrcodes.qrcode')),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'serial_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['serial_number'], name='serial_code_serial__1b91eb_idx'), models.Index(fields=['batch', 'status'], name='serial_code_batch_i_102ad0_idx'), models.Index(fields=['status', '-suspicion_score'], name='serial_code_status_f8a62d_idx'), models.Index(fields=['first_scanned_at'], name='serial_code_first_s_1426ec_idx')],
            },
        ),
    ]
