# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0008_qrcode_eye_color_qrcode_eye_style_qrcode_frame_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialbatch',
            name='destination_url_template',
            field=models.CharField(
                blank=True,
                help_text='URL template with {serial} placeholder for serial number',
                max_length=2048,
            ),
        ),
    ]
