# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0009_alter_serialbatch_destination_url_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialbatch',
            name='eye_style',
            field=models.CharField(
                choices=[('square', 'Square'), ('circle', 'Circle'), ('rounded', 'Rounded'), ('leaf', 'Leaf'), ('diamond', 'Diamond')],
                default='square',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='serialbatch',
            name='eye_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='serialbatch',
            name='gradient_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serialbatch',
            name='gradient_start',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='serialbatch',
            name='gradient_end',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='serialbatch',
            name='gradient_direction',
            field=models.CharField(
                choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('diagonal', 'Diagonal'), ('radial', 'Radial')],
                default='vertical',
                max_length=20,
            ),
        ),
    ]
