# Generated by Django 5.2.11 on 2026-02-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qrcodes", "0010_serialbatch_eye_style_gradient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serialbatch",
            name="export_file_url",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
