# Generated by Django 5.2.11 on 2026-02-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0011_alter_serialbatch_export_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='frame',
            field=models.CharField(choices=[('none', 'None'), ('simple', 'Simple Border'), ('scan_me', 'Scan Me'), ('balloon', 'Speech Balloon'), ('badge', 'ID Badge'), ('phone', 'Phone Mockup'), ('polaroid', 'Polaroid'), ('laptop', 'Laptop Mockup'), ('ticket', 'Event Ticket'), ('card', 'Card'), ('tag', 'Price Tag'), ('certificate', 'Certificate')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='style',
            field=models.CharField(choices=[('square', 'Square'), ('dots', 'Dots'), ('rounded', 'Rounded')], default='square', max_length=20),
        ),
        migrations.AlterField(
            model_name='serialbatch',
            name='frame',
            field=models.CharField(choices=[('none', 'None'), ('simple', 'Simple Border'), ('scan_me', 'Scan Me'), ('balloon', 'Speech Balloon'), ('badge', 'ID Badge'), ('phone', 'Phone Mockup'), ('polaroid', 'Polaroid'), ('laptop', 'Laptop Mockup'), ('ticket', 'Event Ticket'), ('card', 'Card'), ('tag', 'Price Tag'), ('certificate', 'Certificate')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='serialbatch',
            name='style',
            field=models.CharField(choices=[('square', 'Square'), ('dots', 'Dots'), ('rounded', 'Rounded')], default='square', max_length=20),
        ),
    ]
