# Generated by Django 5.2.10 on 2026-01-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0002_notificationsettings_integration_usersession_exportjob"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="user",
            new_name="users_email_4b85f2_idx",
            old_name="users_email_7dfe72_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="users_created_6541e9_idx",
            old_name="users_created_bca51c_idx",
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
    ]
