# Generated by Django 5.2.11 on 2026-02-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="bio_pages_limit",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="plan",
            name="landing_pages_limit",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plan",
            name="retargeting_pixels",
            field=models.BooleanField(default=False),
        ),
    ]
