# Generated by Django 5.2.11 on 2026-02-15 03:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("links", "0003_add_team_fk"),
        ("teams", "0001_team_collab_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingPageTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("thumbnail_url", models.URLField(blank=True, max_length=500)),
                ("blocks", models.JSONField(default=list)),
                ("settings", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "landing_page_templates",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BioPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("avatar_url", models.URLField(blank=True, max_length=500)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("minimal", "Minimal"),
                            ("dark", "Dark"),
                            ("colorful", "Colorful"),
                            ("gradient", "Gradient"),
                            ("professional", "Professional"),
                        ],
                        default="minimal",
                        max_length=20,
                    ),
                ),
                ("background_color", models.CharField(default="#ffffff", max_length=7)),
                ("text_color", models.CharField(default="#111827", max_length=7)),
                ("button_color", models.CharField(default="#f6821f", max_length=7)),
                (
                    "button_text_color",
                    models.CharField(default="#ffffff", max_length=7),
                ),
                (
                    "button_style",
                    models.CharField(
                        choices=[
                            ("rounded", "Rounded"),
                            ("square", "Square"),
                            ("pill", "Pill"),
                            ("outline", "Outline"),
                        ],
                        default="rounded",
                        max_length=20,
                    ),
                ),
                ("social_links", models.JSONField(blank=True, default=list)),
                ("seo_title", models.CharField(blank=True, max_length=60)),
                ("seo_description", models.CharField(blank=True, max_length=160)),
                ("is_published", models.BooleanField(default=False)),
                ("total_views", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bio_pages",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bio_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bio_pages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BioLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("custom_url", models.URLField(blank=True, max_length=2048)),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("thumbnail_url", models.URLField(blank=True, max_length=500)),
                ("position", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("total_clicks", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bio_links",
                        to="links.link",
                    ),
                ),
                (
                    "bio_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="biolinks.biopage",
                    ),
                ),
            ],
            options={
                "db_table": "bio_links",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("blocks", models.JSONField(default=list)),
                ("settings", models.JSONField(default=dict)),
                ("seo_title", models.CharField(blank=True, max_length=60)),
                ("seo_description", models.CharField(blank=True, max_length=160)),
                ("og_image_url", models.URLField(blank=True, max_length=500)),
                ("is_published", models.BooleanField(default=False)),
                ("total_views", models.BigIntegerField(default=0)),
                ("total_conversions", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landing_pages",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landing_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="biolinks.landingpagetemplate",
                    ),
                ),
            ],
            options={
                "db_table": "landing_pages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("block_id", models.CharField(max_length=100)),
                ("data", models.JSONField(default=dict)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "landing_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="biolinks.landingpage",
                    ),
                ),
            ],
            options={
                "db_table": "form_submissions",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
